

cc_binary(
  name = "dummy_fuzz_test",
  srcs = ["dummy_fuzz_test.cc"],
  deps = [
    "@com_google_cloud_spanner_emulator//frontend/server",
    "@com_github_googleapis_google_cloud_cpp_spanner//google/cloud/spanner:spanner_client",
  ]
)
